# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SurplusApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SurplusApp
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Stripe'
  pod 'GoogleSignIn'
  pod 'Plaid'
  pod 'MultiProgressView'
  pod 'Kingfisher', '~> 4.0'

end